id = "monokai-pro-ce"
name = "Monokai Pro (CE)"
version = "1.0.0"
schema_version = 1
authors = ["Erik Br√ºggemann <erik@eobyte.dev>"]
description = "Monokai Pro Community Edition for Zed"
repository = "https://github.com/erik-brueggemann/zed-monokai-pro-ce"
